version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/angel_paradise
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    command: npm run dev

volumes:
  mongo_data:
